# Cancel the domain name binding, for multi site universal
# baseURL = "https://wails.app/"
languageCode = "en-us"
title = "Wails"
googleAnalytics = "UA-139310949-1"
theme = "hugo-theme-learn"
pygmentsCodeFences = true

# English is the default language
defaultContentLanguage = "en"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
# defaultContentLanguageInSubdir= true

[Languages]
[Languages.en]
title = "Wails"
weight = 2
languageName = "English"

[Languages.zh]
title = "Wails"
weight = 1
languageName = "简体中文"

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = "https://github.com/wailsapp/docsv1/edit/master/content/"
  # Author of the site, will be used in meta information
  author = "Lea Anthony"
  # Description of the site, will be used in meta information
  description = "Official Wails Documentation"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "wails"
